name: setup aws
description: "Config AWS"
inputs:
  image_tag:
    description: "AWS ECR image tag"
    required: false
  duplo_token:
    required: true
  task_def:
    required: true
  aws-region:
    required: true
    
runs:
  using: "composite"
  steps:
    - name: aws-jit
      uses: duplocloud/ghactions-aws-jit@master
      with:
        duplo_host: https://reanfoundation.duplocloud.net/
        duplo_token: ${{ inputs.duplo_token }}
        tenant: dev
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-buildx-
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v3
      with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image_tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      shell: bash
      run: echo ${{ steps.docker_build.outputs.digest }}
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.task_def }} \
        --query taskDefinition > task-definition.json
