# This workflow will trigger pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler


name: module-CI-CD

## Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  workflow_dispatch:
  
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read

jobs:
  Deploy-ECS:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/} | sed "s/\\//-/g")" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repo_name=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_OUTPUT  

      - name: Another step
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"
          echo "Repo: ${{ steps.vars.outputs.repo_name }}"
          

      - name: setup aws and build image
        id: image
        uses: KansoCloud/kanso-build-and-push@v1.0.0
        with:
          Cloud: Duplo
          tenant: dev
          duplo_token: ${{ secrets.DUPLOCLOUD_TOKEN }}
          image_tag: reancare-service-dev-uat:${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          task_def: ${{ secrets.TASK_DEFINTION_NAME }}
          
      - run: echo ${{ steps.image.outputs.image }}
          
          
          
          
          
          
          
#           duplo_token:  ${{ secrets.DUPLOCLOUD_TOKEN }}
#           aws-region: ${{ secrets.AWS_REGION }}
#           image_tag: reancare-service-dev-uat:${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
#           task_def: ${{ secrets.TASK_DEFINTION_NAME }}
#           service_name: duploservices-dev-rcapi-new
#           service_name: ${{ secrets.SERVICE_NAME }} 
  



