name: docker-test

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Build and load
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: user/app:test
        
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: user/app:test
          dockerfile: ./Dockerfile
          annotations: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
#       - name: Run Dockle for vulnerability scan
#         id: dockle
#         uses: docker://checkmarx/dockle-action:v1
#         with:
#           flags: -o json

#       - name: Display Dockle results
#         run: |
#           echo "${{ steps.dockle.outputs.result }}"
